### DISCUSSION TITLE
Night/day lowering of temperature

### DISCUSSION THREAD

**Discussion by endreigesund** [erlendsellie/priceanalyzer#10] [Ideas]
How would you implement this in automation/blueprint and also take into consideration if it's a good idea based on the forecast of price pr hour?

**Comment by erlendsellie** [comment]
![image](https://user-images.githubusercontent.com/18458417/197596668-a5a991a8-5eb5-41e0-b6a3-c9d9935917c1.png)
I've implemented PriceAnalyzer for my Heatpump, which also has night/day/away lowering.

This lowering don't rely on just time, but the Alarm state.
The smart thing though, is to start 'day temperature' a bit before you wake up, when PriceAnalyzer says when it's smart to 'boost'. Then you won't wake up to a cold house, and you start warmup when the price is still low.

Here is a terribly messy template-sensor i use as a base-temp sensor for my heat-pump, which uses a different input_number, based on my alarm state. And if the price is gaining (or better yet, check if the state is 1 for PriceAnalyzer) in the morning, based on a input_datetime , set 'hometemp'.
https://github.com/erlendsellie/HomeAssistantConfig/blob/7944f73bce2edcd7a3f552857448da7b9627ee37/packages/temperatureControl.yaml#L279

Use the new sensor in an automation to update the temperature on a climate-entity, and voila.

A lot of this template sensor is old stuff, from before i developed PriceAnalyzer. This could be done a lot easier now, by utilizing the PriceAnalyzer state and attributes :-)

**Comment by erlendsellie** [comment]
Or did you want this functionality in the core functionality in PriceAnalyzer?

I'm thinking about implementing a service-call or something, to be able to subtract or add some degrees to the analyzer-state from an automation, which could solve this as well, on the integration-level.

I also want to add a service call to be able to change how many degrees priceanalyzer change the thermostat by. So you can choose to boost the thermostat by 2 degrees, and save with 4 degrees, with an automation, depending on the max price for the day, for example.

**Comment by overas** [comment]
@endreigesund, I have done the night and day lowering of the temperature with HA automation. 

First I made a automation to change the set point temperature with the helper: "input_number.set_temperatur_23_grader". When it is night (binary_sensor.natt_22_00_05_00 = on) the temperature lower three degree to 20 degree Celsius, but in the daytime (binary_sensor.natt_22_00_05_00 = off) it rise to normal set point temperature (23 degree Celsius).

```
alias: "Priceanalyser: Endre set temperatur 23 grader"
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.ferie
      - binary_sensor.natt_22_00_05_00
      - binary_sensor.regulator_padrag_under_3
  - platform: homeassistant
    event: start
condition: []
action:
  - if:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.ferie
            state: "on"
          - condition: state
            entity_id: binary_sensor.natt_22_00_05_00
            state: "on"
          - condition: state
            entity_id: binary_sensor.regulator_padrag_under_3
            state: "on"
    then:
      - service: input_number.set_value
        data:
          value: 20
        target:
          entity_id: input_number.set_temperatur_23_grader
    else:
      - service: input_number.set_value
        data:
          value: 23
        target:
          entity_id: input_number.set_temperatur_23_grader
mode: restart
```

Then I use Erlends blueprint to adjust the climate temperature for my Heatit floor thermostat:

```
alias: PriceAnalyzer - Control Climate Bad1etg
description: ""
use_blueprint:
  path: erlendsellie/priceanalyzer.yaml
  input:
    sensor: sensor.priceanalyzer_kr_sand
    number: input_number.set_temperatur_23_grader
    climate: climate.varmekabel_bad1etg
```
