### DISCUSSION TITLE
Car charging

### DISCUSSION THREAD

**Discussion by overas** [erlendsellie/priceanalyzer#16] [Q&A] [answered]
I want to charge my car from 22:00 to 06:00 with lowest price. I have already made a binary_sensor template using the attributt "is_five_cheapest" and used the binary_sensor in the condition. How can I make a template with only the cheapest prices between 22:00 to 06:00 using Priceanalyzer? 
I want also to thank you for your work with Priceanalyzer. 

```
      - name: "Pricenanalyzer five cheapest today"
        state: >
          {%set current_hour = state_attr('sensor.priceanalyzer_kr_sand', 'current_hour') %}
          {{current_hour.is_five_cheapest}}
```

```
alias: "Easee: Lade bil"
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.easee_home_XXXXX_status
condition:
  - condition: time
    after: "22:00:00"
    before: "06:00:00"
action:
  - if:
      - condition: state
        entity_id: binary_sensor.pricenanalyzer_five_cheapest_today
        state: "on"
    then:
      - service: easee.set_circuit_dynamic_limit
        data:
          device_id: xxxxxxxxxxxxxxxxxxxx
          currentP1: 12
    else:
      - service: easee.set_circuit_dynamic_limit
        data:
          device_id: xxxxxxxxxxxxxxxxxxxx
          currentP1: 0
mode: single
```
